//! Nullstellensatz-lite over 𝔽₂ — bounded-degree infeasibility certificates.
//!
//! Given a CNF `F = C_1 ∧ … ∧ C_m`, the clause polynomials
//! `P_i = clause_poly(C_i)` all evaluate to 0 on every model of F.
//! If F is UNSAT, the ideal generated by `{P_i} ∪ {x² - x}` contains
//! 1 (Nullstellensatz). A degree-`d` Nullstellensatz certificate is
//! a set of polynomials `p_1, …, p_m` with `deg(p_i) + deg(P_i) ≤ d`
//! such that `∑ p_i · P_i ≡ 1 (mod x² - x)`.
//!
//! Finding such a certificate at fixed `d` is linear algebra: the
//! unknowns are the monomial coefficients of each `p_i`. Our encoding:
//!
//! * Monomials: enumerate all multilinear monomials of degree ≤ d.
//!   There are `∑_{k=0..=d} C(n, k)` of them.
//! * Rows (equations): for each monomial `M` of degree ≤ d, the sum
//!   coefficient of `M` in `∑ p_i · P_i` must equal `[M = 1]` (1 for
//!   the empty monomial, 0 for all others).
//! * Columns (unknowns): for each clause `P_i` and each monomial
//!   `μ` of degree ≤ d - deg(P_i), a coefficient `c_{i,μ} ∈ 𝔽₂`.
//!
//! We set up the matrix and solve via Gaussian elimination over 𝔽₂.
//! Non-trivial solutions give a certificate.
//!
//! **Efficiency**: degree d=2 is tractable for n ≤ 50 vars; d=3 for
//! n ≤ 20; d=4 typically infeasible. The Ramsey K_5 width barrier is
//! expected to admit a low-degree certificate (empirical: Tseitin
//! bridging worked at K_5, see project_tseitin_factoring_breakthrough).

use super::poly::{Monomial, Poly};
use std::collections::BTreeMap;

/// One entry in a Nullstellensatz certificate: multiplier polynomial
/// `p_i` attached to clause index `clause_idx`.
#[derive(Clone, Debug)]
pub struct CertTerm {
    pub clause_idx: usize,
    pub multiplier: Poly,
}

/// A full degree-`d` Nullstellensatz certificate: `∑ term.multiplier ·
/// clause_poly(term.clause_idx) ≡ 1`.
#[derive(Clone, Debug)]
pub struct NsCertificate {
    pub degree: usize,
    pub terms: Vec<CertTerm>,
}

#[derive(Debug)]
pub enum NsResult {
    /// Found a certificate: F is UNSAT and the certificate witnesses it.
    Unsat(NsCertificate),
    /// No degree-`d` certificate exists. F may still be UNSAT at
    /// higher degree.
    NoCertificate,
}

/// Enumerate all multilinear monomials of degree exactly `k` on `n` vars
/// (1-indexed, so support ⊆ {1, ..., n}).
fn enumerate_monomials_of_degree(n: u32, k: usize) -> Vec<Monomial> {
    let mut out = Vec::new();
    let vars: Vec<u32> = (1..=n).collect();
    let mut chosen = Vec::with_capacity(k);
    fn rec(
        vars: &[u32],
        start: usize,
        k_left: usize,
        chosen: &mut Vec<u32>,
        out: &mut Vec<Monomial>,
    ) {
        if k_left == 0 {
            out.push(Monomial::from_vars(chosen.iter().copied()));
            return;
        }
        if vars.len() - start < k_left {
            return;
        }
        for i in start..vars.len() {
            chosen.push(vars[i]);
            rec(vars, i + 1, k_left - 1, chosen, out);
            chosen.pop();
        }
    }
    rec(&vars, 0, k, &mut chosen, &mut out);
    out
}

/// All multilinear monomials of degree ≤ `d` on n vars, sorted.
fn enumerate_monomials_up_to(n: u32, d: usize) -> Vec<Monomial> {
    let mut out = Vec::new();
    for k in 0..=d {
        out.extend(enumerate_monomials_of_degree(n, k));
    }
    out.sort();
    out
}

/// Try to find a degree-`d` Nullstellensatz certificate for `F = clauses`
/// over variables `1..=n`. Returns `Unsat(cert)` if found, else `NoCertificate`.
pub fn find_ns_certificate(
    clauses: &[Vec<i32>],
    n: u32,
    d: usize,
) -> NsResult {
    if clauses.is_empty() {
        return NsResult::NoCertificate;
    }

    let clause_polys: Vec<Poly> = clauses.iter().map(|c| Poly::clause_poly(c)).collect();
    let clause_degrees: Vec<usize> = clause_polys.iter().map(|p| p.degree()).collect();
    let monomials = enumerate_monomials_up_to(n, d);
    let mono_index: BTreeMap<Monomial, usize> =
        monomials.iter().cloned().enumerate().map(|(i, m)| (m, i)).collect();

    // Enumerate unknowns: (clause_idx, multiplier_monomial) pairs.
    let mut unknowns: Vec<(usize, Monomial)> = Vec::new();
    for (i, deg_i) in clause_degrees.iter().enumerate() {
        if *deg_i > d {
            continue;
        }
        let budget = d - deg_i;
        for mono in enumerate_monomials_up_to(n, budget) {
            unknowns.push((i, mono));
        }
    }
    if unknowns.is_empty() {
        return NsResult::NoCertificate;
    }

    // Build matrix: rows = monomials (targets), cols = unknowns.
    // entry[row][col] = coefficient of monomial[row] in
    //                   unknowns[col].mono · clause_polys[unknowns[col].clause_idx].
    // RHS: 1 for row = empty-monomial, 0 otherwise.
    let n_rows = monomials.len();
    let n_cols = unknowns.len();
    // Matrix as bit-rows: one Vec<u64> per monomial index, plus one extra
    // bit for the RHS. Bit k of row r is set if column k contributes to
    // row r's constraint.
    let words_per_row = (n_cols + 1 + 63) / 64;
    let mut matrix: Vec<Vec<u64>> = vec![vec![0u64; words_per_row]; n_rows];

    // Fill matrix.
    for (col, (ci, mu)) in unknowns.iter().enumerate() {
        let mu_poly = {
            let mut s = std::collections::BTreeSet::new();
            s.insert(mu.clone());
            Poly(s)
        };
        let product = mu_poly.mul(&clause_polys[*ci]);
        for m in &product.0 {
            if let Some(&row) = mono_index.get(m) {
                let word = col >> 6;
                let bit = col & 63;
                matrix[row][word] ^= 1u64 << bit;
            } // else: higher than d — shouldn't occur given budget.
        }
    }
    // RHS column is at index n_cols.
    let rhs_col = n_cols;
    let rhs_word = rhs_col >> 6;
    let rhs_bit = rhs_col & 63;
    // Row for the empty monomial (Monomial::one) gets RHS = 1.
    let one_row = *mono_index.get(&Monomial::one()).expect("empty monomial");
    matrix[one_row][rhs_word] |= 1u64 << rhs_bit;

    // Gaussian elimination over 𝔽₂.
    // We want any particular solution (not basis). Row-reduce, then
    // back-substitute setting free variables = 0.
    let mut pivot_row_of_col: Vec<Option<usize>> = vec![None; n_cols];
    let mut row = 0usize;
    for col in 0..n_cols {
        // Find a pivot row with bit `col` set, among rows >= `row`.
        let col_word = col >> 6;
        let col_bit = 1u64 << (col & 63);
        let mut pivot: Option<usize> = None;
        for r in row..n_rows {
            if matrix[r][col_word] & col_bit != 0 {
                pivot = Some(r);
                break;
            }
        }
        let pivot = match pivot {
            Some(p) => p,
            None => continue,
        };
        matrix.swap(pivot, row);
        pivot_row_of_col[col] = Some(row);
        // Eliminate bit `col` in all other rows.
        for r in 0..n_rows {
            if r == row {
                continue;
            }
            if matrix[r][col_word] & col_bit != 0 {
                for w in 0..words_per_row {
                    matrix[r][w] ^= matrix[row][w];
                }
            }
        }
        row += 1;
    }

    // Check consistency: every row with all-zero LHS must have RHS = 0.
    for r in 0..n_rows {
        let mut all_zero_lhs = true;
        for c in 0..n_cols {
            let w = c >> 6;
            let b = 1u64 << (c & 63);
            if matrix[r][w] & b != 0 {
                all_zero_lhs = false;
                break;
            }
        }
        if all_zero_lhs {
            let has_rhs = matrix[r][rhs_word] & (1u64 << rhs_bit) != 0;
            if has_rhs {
                // Inconsistent: no solution at this degree.
                return NsResult::NoCertificate;
            }
        }
    }

    // Extract solution: free variables = 0, pivot variables = RHS of
    // their pivot row.
    let mut solution = vec![false; n_cols];
    for (col, pr) in pivot_row_of_col.iter().enumerate() {
        if let Some(pivot_row) = pr {
            let has_rhs = matrix[*pivot_row][rhs_word] & (1u64 << rhs_bit) != 0;
            solution[col] = has_rhs;
        }
    }

    // Build certificate from non-zero entries.
    let mut multipliers: BTreeMap<usize, Poly> = BTreeMap::new();
    for (col, val) in solution.iter().enumerate() {
        if !*val {
            continue;
        }
        let (ci, mu) = &unknowns[col];
        let entry = multipliers.entry(*ci).or_insert_with(Poly::zero);
        let mu_poly = {
            let mut s = std::collections::BTreeSet::new();
            s.insert(mu.clone());
            Poly(s)
        };
        entry.add_assign(&mu_poly);
    }
    let terms: Vec<CertTerm> = multipliers
        .into_iter()
        .filter(|(_, p)| !p.is_zero())
        .map(|(clause_idx, multiplier)| CertTerm { clause_idx, multiplier })
        .collect();

    if terms.is_empty() {
        return NsResult::NoCertificate;
    }
    NsResult::Unsat(NsCertificate { degree: d, terms })
}

/// Verify a certificate by direct evaluation: compute `∑ p_i · P_i`
/// and check it equals 1.
pub fn verify_certificate(cert: &NsCertificate, clauses: &[Vec<i32>]) -> bool {
    let mut acc = Poly::zero();
    for term in &cert.terms {
        let p_i = Poly::clause_poly(&clauses[term.clause_idx]);
        let contrib = term.multiplier.mul(&p_i);
        acc.add_assign(&contrib);
    }
    acc.is_one()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trivial_unsat_has_degree_1_certificate() {
        // F = (x1) ∧ (¬x1). Clause polys: (1-x1) = 1+x1 and x1.
        // Sum: x1 + 1 + x1 = 1. Coefficients both 1.
        let clauses = vec![vec![1], vec![-1]];
        let res = find_ns_certificate(&clauses, 1, 1);
        match res {
            NsResult::Unsat(cert) => {
                assert!(verify_certificate(&cert, &clauses));
            }
            _ => panic!("expected UNSAT cert"),
        }
    }

    #[test]
    fn sat_formula_has_no_certificate() {
        // F = (x1 ∨ x2). SAT. No degree-≤-d certificate can exist.
        let clauses = vec![vec![1, 2]];
        for d in 1..=3 {
            match find_ns_certificate(&clauses, 2, d) {
                NsResult::Unsat(_) => panic!("spurious certificate at d={}", d),
                NsResult::NoCertificate => {}
            }
        }
    }

    #[test]
    fn pigeonhole_2_1_is_degree_2() {
        // F: pigeon 1 in hole 1 or 2 (x1 ∨ x2); pigeon 2 in 1 or 2
        // (x3 ∨ x4); at-most-one in each hole:
        // hole 1: ¬x1 ∨ ¬x3; hole 2: ¬x2 ∨ ¬x4.
        // Wait — this is 2-hole / 2-pigeon, which is SAT. PH_{3,2}
        // (3 pigeons, 2 holes) is UNSAT. For simplicity test triangle
        // inconsistency instead.
        //
        // Triangle UNSAT: x1, x2, ¬(x1 ∧ x2). I.e., x1, x2, ¬x1 ∨ ¬x2.
        let clauses = vec![vec![1], vec![2], vec![-1, -2]];
        let res = find_ns_certificate(&clauses, 2, 2);
        match res {
            NsResult::Unsat(cert) => {
                assert!(verify_certificate(&cert, &clauses));
            }
            _ => panic!("expected UNSAT cert at degree 2"),
        }
    }

    #[test]
    fn r_3_3_k_3_is_sat() {
        // K_3 has one triangle. Triangle ban (red OR blue): not both
        // monochromatic, so the edges can be colored. F is SAT.
        let clauses = vec![
            vec![-1, -2, -3], // red ban
            vec![1, 2, 3],    // blue ban
        ];
        match find_ns_certificate(&clauses, 3, 2) {
            NsResult::NoCertificate => {} // expected: F is SAT
            NsResult::Unsat(c) => {
                // Verify whether the certificate is actually valid;
                // if verify_certificate returns false we can reject.
                let valid = verify_certificate(&c, &clauses);
                assert!(!valid, "spurious UNSAT certificate for SAT instance");
            }
        }
    }

    #[test]
    fn enumerate_monomials_count() {
        // n=3, d=2: 1 + 3 + 3 = 7.
        assert_eq!(enumerate_monomials_up_to(3, 2).len(), 7);
        // n=4, d=2: 1 + 4 + 6 = 11.
        assert_eq!(enumerate_monomials_up_to(4, 2).len(), 11);
    }
}
