//! Schreier-Sims algorithm — strong generating set + stabilizer chain.
//!
//! Given generators of a permutation group G and a base sequence of
//! points `b_1, b_2, …, b_L`, builds a stabilizer chain:
//!
//! ```text
//!     G = G_0 ≥ G_1 ≥ … ≥ G_L = {id}
//! ```
//!
//! where `G_i = Stab(b_1, …, b_i)`. For each level, we store:
//!   * The orbit of `b_{i+1}` under `G_i`.
//!   * A Schreier tree: for each orbit element `β`, the group element
//!     `u_β` (coset representative) such that `u_β(b_{i+1}) = β`.
//!
//! # Usage for sound orbit closure
//!
//! Given a clause `C` justified via some generator `g`, we want to
//! emit `g'(C)` for another group element `g'` with a VALID VeriPB
//! witness. The Schreier-Sims decomposition lets us express any `g'`
//! as a product of coset representatives. Each coset representative
//! is itself a generator (or product of generators) with known
//! VeriPB justification.
//!
//! The simpler use: select a **strong generating set** (SGS) that's
//! COMPATIBLE with lex-leader canonicality. Using SGS generators
//! instead of satsuma's raw generator set makes the per-gen lex-leader
//! semantically tighter and potentially overlay-compatible.

use super::generators::Permutation;
use std::collections::{HashMap, VecDeque};

/// One level of the stabilizer chain.
#[derive(Clone, Debug)]
pub struct StabLevel {
    /// The base point at this level.
    pub base_point: u32,
    /// Orbit of base_point under G_i.
    pub orbit: Vec<u32>,
    /// Schreier tree: maps orbit element β → coset representative u_β
    /// such that u_β(base_point) = β. u_{base_point} = identity.
    pub coset_reps: HashMap<u32, Permutation>,
}

/// Complete Schreier-Sims data structure.
#[derive(Clone, Debug)]
pub struct SchreierSims {
    pub base: Vec<u32>,
    pub levels: Vec<StabLevel>,
    /// The strong generating set: union of generators that arise
    /// across all levels. Each element is a non-identity group element
    /// that stabilizes the base prefix above its level.
    pub strong_gens: Vec<Permutation>,
}

/// Compute the orbit of `point` under a set of generators, returning
/// both the orbit elements and the Schreier tree (coset reps as
/// permutations mapping base_point to each orbit element).
fn orbit_and_tree(
    point: u32,
    gens: &[Permutation],
    n_vars: u32,
) -> (Vec<u32>, HashMap<u32, Permutation>) {
    let id = Permutation::identity(n_vars);
    let mut tree: HashMap<u32, Permutation> = HashMap::new();
    tree.insert(point, id);
    let mut queue: VecDeque<u32> = VecDeque::new();
    queue.push_back(point);
    let mut orbit = vec![point];

    while let Some(current) = queue.pop_front() {
        let current_perm = tree[&current].clone();
        for g in gens {
            // β' = g(current_in_base_coords). We need to find where
            // base_point maps to under (g ∘ current_perm).
            // Actually: current_perm maps base_point → current.
            // g maps current → g(current). So (g ∘ current_perm) maps
            // base_point → g(current).
            let image = g.apply_var(current);
            // image is a SIGNED literal. For orbit tracking we use
            // unsigned variable index.
            let image_var = image.unsigned_abs();
            if !tree.contains_key(&image_var) {
                let new_perm = g.compose(&current_perm);
                tree.insert(image_var, new_perm);
                queue.push_back(image_var);
                orbit.push(image_var);
            }
        }
    }
    (orbit, tree)
}

/// "Sift" a permutation through the stabilizer chain. Returns the
/// residual permutation after stripping coset representatives at each
/// level. If the residual is the identity, the permutation is in the
/// group generated by the strong generating set. If non-identity, it's
/// a "new" generator that should be added to extend the SGS.
fn sift(
    perm: &Permutation,
    levels: &[StabLevel],
    n_vars: u32,
) -> Permutation {
    let mut h = perm.clone();
    for level in levels {
        let bp = level.base_point;
        let image = h.apply_var(bp);
        let image_var = image.unsigned_abs();
        match level.coset_reps.get(&image_var) {
            Some(u_beta) => {
                // Strip coset rep: h ← u_β^{-1} ∘ h.
                let u_inv = u_beta.inverse();
                h = u_inv.compose(&h);
            }
            None => {
                // image_var not in orbit → h is NOT in G (or we need
                // to extend the orbit). Return h as non-identity residual.
                return h;
            }
        }
    }
    h
}

impl SchreierSims {
    /// Build the Schreier-Sims stabilizer chain from a set of generators
    /// and a base (variable ordering). The base determines the
    /// stabilizer chain hierarchy.
    ///
    /// Iterates until all Schreier generators sift to identity (i.e.,
    /// the strong generating set is complete).
    pub fn build(
        gens: &[Permutation],
        base: &[u32],
        n_vars: u32,
    ) -> Self {
        if gens.is_empty() || base.is_empty() {
            return Self {
                base: base.to_vec(),
                levels: Vec::new(),
                strong_gens: Vec::new(),
            };
        }

        // Initialize SGS with the input generators.
        let mut sgs: Vec<Permutation> = gens
            .iter()
            .filter(|g| !g.is_identity())
            .cloned()
            .collect();

        let max_iterations = 100;

        for _iter in 0..max_iterations {
            // Build stabilizer chain from current SGS.
            let mut levels = Vec::new();
            let mut level_gens = sgs.clone();

            for &bp in base {
                if level_gens.is_empty() {
                    break;
                }
                let (orbit, tree) = orbit_and_tree(bp, &level_gens, n_vars);
                levels.push(StabLevel {
                    base_point: bp,
                    orbit,
                    coset_reps: tree,
                });
                // Generators for the next level: those that FIX bp.
                level_gens.retain(|g| {
                    let img = g.apply_var(bp);
                    img == bp as i32 // fixed point (same var, same polarity)
                });
            }

            // Generate Schreier generators and sift. A Schreier generator
            // for level i is: u_{g(β)}^{-1} ∘ g ∘ u_β for each orbit
            // element β and generator g at level i.
            let mut new_gens_found = false;
            // Collect Schreier generators into a buffer (avoids borrow
            // conflict with sgs).
            let mut schreier_residuals: Vec<Permutation> = Vec::new();
            for li in 0..levels.len() {
                let level = &levels[li];
                let active_gens: Vec<Permutation> = sgs
                    .iter()
                    .filter(|g| {
                        for j in 0..li {
                            let bp_j = levels[j].base_point;
                            if g.apply_var(bp_j) != bp_j as i32 {
                                return false;
                            }
                        }
                        true
                    })
                    .cloned()
                    .collect();

                for &beta in &level.orbit {
                    let u_beta = &level.coset_reps[&beta];
                    for g in &active_gens {
                        let g_beta_lit = g.apply_var(beta);
                        let g_beta = g_beta_lit.unsigned_abs();

                        if let Some(u_g_beta) = level.coset_reps.get(&g_beta) {
                            let s = u_g_beta.inverse().compose(&g.compose(u_beta));
                            if !s.is_identity() {
                                let residual = sift(&s, &levels, n_vars);
                                if !residual.is_identity() {
                                    schreier_residuals.push(residual);
                                }
                            }
                        }
                    }
                }
            }
            if schreier_residuals.is_empty() {
                // SGS is complete.
                return Self {
                    base: base.to_vec(),
                    levels,
                    strong_gens: sgs,
                };
            }
            new_gens_found = true;
            sgs.extend(schreier_residuals);

            if !new_gens_found {
                // SGS is complete.
                return Self {
                    base: base.to_vec(),
                    levels,
                    strong_gens: sgs,
                };
            }
        }

        // Fallback: return whatever we have after max iterations.
        let mut levels = Vec::new();
        let mut level_gens = sgs.clone();
        for &bp in base {
            if level_gens.is_empty() {
                break;
            }
            let (orbit, tree) = orbit_and_tree(bp, &level_gens, n_vars);
            levels.push(StabLevel {
                base_point: bp,
                orbit,
                coset_reps: tree,
            });
            level_gens.retain(|g| g.apply_var(bp) == bp as i32);
        }
        Self {
            base: base.to_vec(),
            levels,
            strong_gens: sgs,
        }
    }

    /// Compute the group order from the stabilizer chain:
    /// |G| = ∏ |orbit_i|.
    pub fn group_order(&self) -> u64 {
        self.levels.iter().fold(1u64, |acc, l| acc.saturating_mul(l.orbit.len() as u64))
    }

    /// Sift a permutation through the chain. Returns true if the
    /// permutation is in the group.
    pub fn is_member(&self, perm: &Permutation, n_vars: u32) -> bool {
        sift(perm, &self.levels, n_vars).is_identity()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_group_has_empty_sgs() {
        let ss = SchreierSims::build(&[], &[1, 2], 3);
        assert!(ss.strong_gens.is_empty());
        assert_eq!(ss.group_order(), 1);
    }

    #[test]
    fn single_transposition_order_2() {
        // Group generated by swap(1,2) has order 2.
        let g = Permutation::from_mapping(3, &[(1, 2), (2, 1)]);
        let ss = SchreierSims::build(&[g], &[1, 2, 3], 3);
        assert_eq!(ss.group_order(), 2);
    }

    #[test]
    fn s3_from_two_generators() {
        // S_3 = <(1 2), (1 2 3)>. Order 6.
        let swap = Permutation::from_mapping(3, &[(1, 2), (2, 1)]);
        let cycle = Permutation::from_mapping(3, &[(1, 2), (2, 3), (3, 1)]);
        let ss = SchreierSims::build(&[swap, cycle], &[1, 2, 3], 3);
        assert_eq!(ss.group_order(), 6);
    }

    #[test]
    fn s4_order_24() {
        // S_4 = <(1 2), (1 2 3 4)>.
        let swap = Permutation::from_mapping(4, &[(1, 2), (2, 1)]);
        let cycle = Permutation::from_mapping(4, &[(1, 2), (2, 3), (3, 4), (4, 1)]);
        let ss = SchreierSims::build(&[swap, cycle], &[1, 2, 3, 4], 4);
        assert_eq!(ss.group_order(), 24);
    }

    #[test]
    fn membership_test() {
        let swap12 = Permutation::from_mapping(3, &[(1, 2), (2, 1)]);
        let cycle = Permutation::from_mapping(3, &[(1, 2), (2, 3), (3, 1)]);
        let ss = SchreierSims::build(&[swap12.clone(), cycle.clone()], &[1, 2, 3], 3);

        // swap(1,3) should be in S_3.
        let swap13 = Permutation::from_mapping(3, &[(1, 3), (3, 1)]);
        assert!(ss.is_member(&swap13, 3));

        // Identity is in every group.
        assert!(ss.is_member(&Permutation::identity(3), 3));

        // A permutation on 4 vars shouldn't work here (different n_vars).
        // Test within the group: the 3-cycle (2 3 1) should be a member.
        let cycle231 = Permutation::from_mapping(3, &[(1, 3), (2, 1), (3, 2)]);
        assert!(ss.is_member(&cycle231, 3));
    }

    #[test]
    fn compose_produces_correct_results() {
        let swap = Permutation::from_mapping(3, &[(1, 2), (2, 1)]);
        let cycle = Permutation::from_mapping(3, &[(1, 2), (2, 3), (3, 1)]);

        // swap ∘ cycle: first apply cycle (1→2, 2→3, 3→1), then swap (1↔2).
        // So: 1 →cycle 2 →swap 1 = 1. 2 →cycle 3 →swap 3 = 3. 3 →cycle 1 →swap 2 = 2.
        // Result: (2 3) transposition.
        let composed = swap.compose(&cycle);
        assert_eq!(composed.apply_var(1), 1);
        assert_eq!(composed.apply_var(2), 3);
        assert_eq!(composed.apply_var(3), 2);
    }
}
